# Generated by Django 5.1.4 on 2024-12-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('job_details', models.TextField()),
            ],
        ),
    ]
